import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

export const metadata = {
  title: "Hero Kidzz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} antialiased`}>
      <body className="min-h-full flex flex-col">
        <header className="py-4 md:w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>
        <main className="py-4 md:w-11/12 mx-auto">{children}</main>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
